### ISSUE TITLE
Bug: Changing annotation `disco/record` does not delete the old record from Designate

### ISSUE THREAD

**Issue by IvoGoman** [sapcc/disco#14]
Initially, I had added the following annotations to a service of type LoadBalancer:

```yaml
metadata:
  annotations:
    disco: "true"
    disco/record: myhost.zone.tld.
    disco/record-type: A
```
The A record was successfully created in designate.

Then I realised the record needed to be prefixed with `ingress`.

```yaml
metadata:
  annotations:
    disco: "true"
    disco/record: ingress.myhost.zone.tld.
    disco/record-type: A
```

DISCO now updated the Record CR in the cluster and created a new Record in Designate. However, the old record without the `ingress` prefix was abandoned by the controller.

My expectation would have been that DISCO removes the first record as well as, creating the new record.
